### ISSUE TITLE
Системный бар закрывает часть видео в оконном режиме 

### ISSUE THREAD

**Issue by TheSainEyereg** [Viiprogrammer/anilibrix#1]
[Открыл issue](https://github.com/pavloniym/anilibrix/issues/65) в оригинальной репе, но та выглядит слегка заброшенной, поэтому дублирую ещё и сюда. Системный бар закрывает собой часть плеера. В полноэкранном, понятное дело, такой проблемы нет.

### Пример
Бар есть:
![image](https://github.com/pavloniym/anilibrix/assets/37226226/fce5690f-99fe-4f4f-90b3-09e46e6f1951)

Бар убран через `display: none` для демонстрации:
![image](https://github.com/pavloniym/anilibrix/assets/37226226/40bfcffc-bc43-410d-abc8-22bbabcd8629)

**Comment by Viiprogrammer** [comment]
Такс, ну то что закрывает, я понимаю. А что сделать то?)

Могу предложить попробовать добавить скрытие его, когда нет активности в плеере (курсор не двигается), как с интерфейсом плеера

**Comment by TheSainEyereg** [comment]
> Такс, ну то что закрывает, я понимаю. А что сделать то?)
> 
> Могу предложить попробовать добавить скрытие его, когда нет активности в плеере (курсор не двигается), как с интерфейсом плеера

Та не, там можно тупо с CSS пошаманить. Я бы сделал, но у меня какие-то траблы с VSкой у старого node-gyp

**Comment by Viiprogrammer** [comment]
> > Такс, ну то что закрывает, я понимаю. А что сделать то?)
> > Могу предложить попробовать добавить скрытие его, когда нет активности в плеере (курсор не двигается), как с интерфейсом плеера
> 

> Та не, там можно тупо с CSS пошаманить. Я бы сделал, но у меня какие-то траблы с VSкой у старого node-gyp

Попробуй поставить в папке проекта через `npm i node-gyp`, бывало проблема решалась, но основная проблема там из-за `node-fibbers`, которые не обосновано тащит electron-vue, а он в свою очередь заброшен и никак не поддерживается.

Если получится показать на видео (OBS Studio, bandicam). Или как то описать конкретные свойства которые хочется применить к элементам, то я думаю этот вопрос можно решить.

Показывать можно прямо в инструментах разработчика открыв их в собранном приложении в нижней части меню настроек.

![image](https://github.com/AnimeHaze/anilibrix/assets/17622604/e20516f1-1fcf-4eb4-969f-e4687f2187b3)

**Comment by Viiprogrammer** [comment]
Закрыто за отсутствием активности
