### ISSUE TITLE
пропадают поля с данными

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#10]
при первом переходе на страницу релиза отображаются поля со списками тех, кто озвучивал, переводил, оформлял и таймил.
если зайти в просмотр, а затем вернуться на страницу с релизом, эти поля пропадают. если выйти в избранное, а затем снова зайти в релиз, то поля не появляются.
если закрыть приложение и снова запустить, поля в релизе появляются, но стоит зайти в просмотр и вернуться на страницу релиза, все снова исчезает до следующей перезагрузки приложения.
версия сборки приложения v1.4.3-ext.7
работает на OS win10 pro ver 22H2 build 19045.2846
![img](https://github.com/AnimeHaze/anilibrix/assets/84020873/3afc143d-4650-446f-881a-a452fea76578)

**Comment by Viiprogrammer** [comment]
Исправлено в https://github.com/AnimeHaze/anilibrix/commit/6420bca15453654909eaba65c0629334dd86fa88
