### ISSUE TITLE
не работает функционал "переместить кнопки вправо"

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#11]
нет реакции на ползунок "переместить кнопки вправо". в каком бы положении этот ползунок не был в настройках, на win10 кнопки всегда расположены справа (как во всех окнах на windows).
версия сборки приложения v1.4.3-ext.7
версия OS win10 pro ver 22H2 build 19045.2846 (если это важно)

**Comment by Viiprogrammer** [comment]
Приложение определяет положение кнопок в зависимости от системы, тогл предназначен для того что бы сдвинуть кнопки вправо если они по какой-то причине определились, так что отображаются слева. Фактически это ожидаемое поведение, Какое предложение? 

Скрывать этот функционал для систем с правосторонним расположением?
Изменить на селект с выбором положения?

**Comment by azrylio** [comment]
@Viiprogrammer, ага, теперь, наверное, понял, как оно должно работать по задумке. до этого я думал, что оно просто должно перемещать кнопки по желанию юзера (если по какой-то причине не устроило их положение).

мне кажется, что располагать кнопки управления окном в Win слева как-то нелогично, когда у всех остальных окон они справа (собственно как и в MacOS сдвигать кнопки вправо, когда у всех окон они слева, выбивается из общего контекста). и, если я верно понял ваше сообщение выше, сейчас оно работает так, как и задумано, в Win кнопки справа и toggle sw их не перемещает (с чем я абсолютно солидарен). а нужен этот переключатель только для того, чтобы направить кнопки туда, где им место в соответствии с ОС, если по каким-то причинам это не произошло автоматом.

не сочтите, пожалуйста, что я придираюсь. я просто не понял задумки и подумал, что это баг, потому и создал issue. если переключатель нужен, то пусть останется и выполняет свои функции как и задумано.

большое спасибо за ваш труд и за то, что учитываете репорты и совершенствуете приложение. пользуюсь с удовольствием и не планирую слезать)

**Comment by Viiprogrammer** [comment]
> не сочтите, пожалуйста, что я придираюсь. я просто не понял задумки и подумал, что это баг, потому и создал issue. если переключатель нужен, то пусть останется и выполняет свои функции как и задумано.

Никаких проблем) я подумывал скрывать его, но как то решил что может и не нужно

спасибо за фидбэк
