### ISSUE TITLE
[Request] Добавить настройку Proxy.

### ISSUE THREAD

**Issue by jsynth** [Viiprogrammer/anilibrix#13]
Будет здорово если добавишь настройки прокси аля qt клиент. Смогу смотреть на работе, _хаха_.

**Comment by Viiprogrammer** [comment]
А когда работать?)

**Comment by jsynth** [comment]
ничего, работа не волк, а вот бэклог всё больше и больше :)

**Comment by Viiprogrammer** [comment]
Пока не могу предложить полноценный прокси, но API и статику может проксировать https://anilibria.animehaze.me/ (если указать в настроках прилы), сколько оно проживет если честно не скажу, ибо сервер предоплачен, и просто сдохнет когда оплата пройдет

**Comment by jsynth** [comment]
да не, мне нужны настройки прокси не для обхода блокировок, а показать приложухе где доступ в интернет. Комп в подсети и гейт в условном 192,168,2,14:3128. Кароч пока так не сделаю ничего не работает.
![изображение](https://github.com/AnimeHaze/anilibrix-plus/assets/9024762/5b9a6ad1-70ba-4f03-b691-ff56b74b00f0)

**Comment by Viiprogrammer** [comment]
Я собрал версию, которая добавляет поддержку http-proxy, но торренты скорее всего работать не будут https://t.me/anilibrix_plus_beta/4 . Жду твой фидбэк

**Comment by jsynth** [comment]
торренты у меня и так заблокированы)
И так, на Win10 x32 всё (каталог, логин, видео) отлично заработало! В настройках более ничего неменял.

**Comment by Viiprogrammer** [comment]
Отлично. Будет добавлено в `1.4.3-ext.11`
