### ISSUE TITLE
[Предложение]  Сделать постер на страничке тайтла не круглой, а прямоугольной формы

### ISSUE THREAD

**Issue by XlebyshekGG** [Viiprogrammer/anilibrix#14]
Не знаю каким место думали разработчики приложения, когда решили сделать постер круглой формы...
![image](https://github.com/AnimeHaze/anilibrix/assets/131394277/e0f8461f-abe0-46a6-aff8-e778e9b526af)

**Comment by Viiprogrammer** [comment]
Закрыто с ad327f1604a3216e7f85bef64a8da6dba65411fb
