### ISSUE TITLE
[Баг] Не весь постер вмещается во вкладке "РЕЛИЗЫ"

### ISSUE THREAD

**Issue by XlebyshekGG** [Viiprogrammer/anilibrix#15]
![Снимок экрана 2023-12-03 020457 копия](https://github.com/AnimeHaze/anilibrix/assets/131394277/3a900b61-8384-4229-9d32-287b98493071)

**Comment by XlebyshekGG** [comment]
Только сейчас понял, что это косяк адаптации приложения к экрану😅

**Comment by Viiprogrammer** [comment]
> Только сейчас понял, что это косяк адаптации приложения к экрану😅

На самом деле да... это такой прикол маштабирования в приложении...

Не баг, а фича получается
