### ISSUE TITLE
[ПРЕДЛОЖЕНИЕ] Поведение плеера при перемотке клавишами

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [Viiprogrammer/anilibrix#2]
Описание:

Бывает такое что нужно поставить серию на паузу немного перемотать с помощью клавиш со стрелками и через некоторое время продолжить просмотр, но по какой то причине если перемотать серию вперёд или назад когда стоит пауза то после перемотки начнется воспроизведение. 

Предложение:

Сделать так что если серия стоит на паузе и произошла перемотка с помощью клавиш со стрелками вперёд или назад то пауза останется

**Comment by Viiprogrammer** [comment]
Добавлено в https://github.com/AnimeHaze/anilibrix/commit/676f468c47d8abd760da5476b0a5bec5021cfe99
