### ISSUE TITLE
[Фикс] Полоска перемотки

### ISSUE THREAD

**Issue by Keenelge** [Viiprogrammer/anilibrix#22]
С какого-то патча на полоске перемотке стало невозможным перематывать кликом на момент, которые находится рядом с "шариком перемотки"

Ниже описание проблемы, но коротко говоря: нужно уменьшить реальный размер "шарика" на таймлайне при просмотре

Я могу перематывать стрелочками, но бывают моменты, когда хочу перемотать мышкой, я могу это сделать зажав "шарик" и перенести на момент, который хочу, но большую часть просто хочется нажать на таймлайн в нужном месте и это работает хорошо до момента, когда "нужное место" находится несколько секунд назад/впереди т.к. с какого-то патча изменился реальный размер шарика (т.е. отрисовывается он одним размером, но захватывает большую область вокруг себя), и когда кликаешь рядом с ним он всё равно захватывает курсор и вместо перемотки на нужное место он ничего не делает.

**Comment by Viiprogrammer** [comment]
Оф версия подвержена проблеме?  Явных изменений небыло,  возможно изменения vuetify

**Comment by Keenelge** [comment]
> Оф версия подвержена проблеме? Явных изменений небыло, возможно изменения vuetify

На офе всё норм работает. Да и на этой версии я точно помню, что это произошло после того, как я установил обновление. К сожалению не помню когда это произошло, но ориентировочно где-то осенью, не раньше

**Comment by Viiprogrammer** [comment]
> > Оф версия подвержена проблеме? Явных изменений небыло, возможно изменения vuetify
> 
> На офе всё норм работает. Да и на этой версии я точно помню, что это произошло после того, как я установил обновление. К сожалению не помню когда это произошло, но ориентировочно где-то осенью, не раньше

Отлично, спасибо за фидбэк, буду смотреть

**Comment by Viiprogrammer** [comment]
Проблема действительно присутствует и воспроизводится, попробую сделать патч в след версии

**Comment by Viiprogrammer** [comment]
Исправлено в 6d857d7bbf5dfd1e1f073434143f97e0b7a1e4a2

Не понимаю почему, но библиотека компонентов которую использует либрикс в минорном или патч релизе изменила поведение слайдера. Я зафиксировал версию на уровне той которая использовалась для сборки официального релиза. 

Я не уверен, что баг, скорее фича, а перематывать можно удерживая и перетаскивая, но я поддерживаю данное решение и откатываюсь до старой версии с фиксацией, все равно обновлять ее нет особого резона.

Соре что такой простой ишью так долго решался.
