### ISSUE TITLE
(Bug) не прогружается постер в Discord RPC

### ISSUE THREAD

**Issue by xdenotte** [Viiprogrammer/anilibrix#23]
Не прогружается картинка в профиле дискорда на любом тайтле
![изображение](https://github.com/AnimeHaze/anilibrix-plus/assets/73490483/b86f23d9-a7ca-4d2e-b8e5-69b2d27329ab)

**Comment by Viiprogrammer** [comment]
Проблема заключается судя по всему в том, что недавно анилибрия побанила доступ с проксей (по крайней мере некоторых по какому-то принципу), а дискорд пробрасывает картинку через свой прокси `https://media.discordapp.net/external/%TOKEN%/https/anilibriaqt.anilib.top/storage/releases/posters/9612/GeDhYkbfsNgK0nUd__6c07a4bc7c9fe2e669c16064e46947c7.jpg` в итоге она становится битая

Это можно исправить только с их стороны или же юзать свои зеркала в приложении, где отсутствует такой блок. Сейчас это например - [https/anilibria.animehaze.me/](https/anilibria.animehaze.me/) однако он будет работать до того пока сервер оплачен и рано или поздно умрет

Достаточно указать как сервер статики, как API не обязательно 
![image](https://github.com/AnimeHaze/anilibrix-plus/assets/17622604/614dc99a-d4f6-4178-88fb-a57cc8123767) (поле имеет ввод текста, не обязательно выбирать только то что есть)

**Comment by Viiprogrammer** [comment]
Как заметка - проблема только на "сторонних" зеркалах, в них не входит

https://anilibria.tv
https://static.anilibria.tv/
https://static.wwnd.space/
https://static-libria.weekstorm.one
https://anilibria.top

все их можно использовать для сервера статики и все они корректно выводят постер
