### ISSUE TITLE
Улучшение DRPC

### ISSUE THREAD

**Issue by delyfss4796** [Viiprogrammer/anilibrix#25]
Убрать "Смотрит аниме" и переместить осталось tt:tt на 2 лайн избавившись от кривого таймштампа

**Comment by xdenotte** [comment]
Да, можно кстати добавить отображение паузы, по типу когда плеер на паузе то чтобы в профиле там где Осталось xx:xx автоматически менялось на "На паузе", потому что сейчас просто секунды скачут то вперед то назад.

**Comment by Viiprogrammer** [comment]
Жду фидбэк по бетке https://t.me/anilibrix_plus_beta/26

**Comment by xdenotte** [comment]
Все отлично)

**Comment by delyfss4796** [comment]
> Жду фидбэк по бетке https://t.me/anilibrix_plus_beta/26

добавь релиз, снап фууу
udp: а оно в тгк

**Comment by delyfss4796** [comment]
ой

**Comment by delyfss4796** [comment]
Можно еще удалить буттон anilibria.tv ибо в любом случае нижний буттон ведет на их сайт

**Comment by Viiprogrammer** [comment]
> Можно еще удалить буттон anilibria.tv ибо в любом случае нижний буттон ведет на их сайт

В принципе можно, прост там можно было 2 кнопки))) вот я тогда и впердолил обе, для максимальной утилизации))

**Comment by AzekClark** [comment]
Можно ещё добавить фишку чтобы anlibtix в drpc не писал когда он просто открыт, а включался только когда смотришь серию. Или сделать эту фишку по тоглу.

**Comment by Viiprogrammer** [comment]
> Можно ещё добавить фишку чтобы anlibtix в drpc не писал когда он просто открыт, а включался только когда смотришь серию. Или сделать эту фишку по тоглу.

Сделал по умолчанию с 9d461d5cbc1b4956ddca9fd79a14e92d654edd18
