### ISSUE TITLE
Баг с изменением размера окна функции "Картинка в картинке"

### ISSUE THREAD

**Issue by xdenotte** [Viiprogrammer/anilibrix#28]
При изменении размера окна "Картинка в картинке" окно улетает в правую сторону 
Вот видео пример:https://youtu.be/qyLApuXdtx0
Версия:1.4.3.0 ext12

**Comment by delyfss4796** [comment]
Странно на линухе такого нет

**Comment by Viiprogrammer** [comment]
> При изменении размера окна "Картинка в картинке" окно улетает в правую сторону Вот видео пример:https://youtu.be/qyLApuXdtx0 Версия:1.4.3.0 ext12

Что-то такое видал когда сидел на винде, у меня было два монитора (мб как то связано)

Но вот исправить - это конечно интересный вопрос. Видать какой то баг хромиума.

**Comment by Viiprogrammer** [comment]
Достаточно странный баг, и не менее забавно то как Windows 11 видит PiP в панели задач (как отдельный значок приложения), хотя например в Edge такого поведения не наблюдается. На баг не похоже, вероятнее всего это нюансы изменения Win API и устаревший API в версии Enectron у приложения. (Просто предположение).

Баг воспроизвести не могу, да и если бы смог это скорее проблема в электроне, можно если в будущем апнем версию, то что-то да и выйдет (само исправится).

Воспроизводить  пытался на:

Выпуск	Windows 11 Pro
Версия	23H2
Дата установки	‎05.‎12.‎2023
Сборка ОС	22631.3737
Взаимодействие	Windows Feature Experience Pack 1000.22700.1009.0

Так как решения не предвидится, а воспроизвести сложно, закрываю.
