### ISSUE TITLE
релиз с официальной озвучкой не помечается как просмотренный

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#3]
релиз, который озвучивается официально, не скрывается в списке избранного, если отметить его как просмотренный.
серии таких релизов не представлены в плеере (из-за их официальности), их можно смотреть только на офф ресурсах. но хотелось бы, чтобы он оставался в избранном (для истории) и при этом скрывался, как любой просмотренный релиз.
![Capture2](https://github.com/AnimeHaze/anilibrix/assets/84020873/0afc8fc5-df4f-4e57-ad86-2bf3bc8524e1)

**Comment by Viiprogrammer** [comment]
Скрытие происходит по принципу проверки отмеченных серий, а так, как серий нет, "отметить как просмотренное" по сути никак не отрабатывает и ни к чему не приводит.

У меня есть идеи как это можно решить. Принято.
