### ISSUE TITLE
Ошибка загрузки релизов на версиях до 1.4.3.ext13 включительно

### ISSUE THREAD

**Issue by AlexanderShad** [Viiprogrammer/anilibrix#30]
Доброго времени суток.

Почему-то не работает на Fedora 40, сам Анилибриск, нормально работает, а Анилибрик-плюс пишет не может получить список релизов... 

С уважением

**Comment by Viiprogrammer** [comment]
> Доброго времени суток.
> 
> Почему-то не работает на Fedora 40, сам Анилибриск, нормально работает, а Анилибрик-плюс пишет не может получить список релизов...
> 
> С уважением

Это недавняя проблема из-за изменения серверов анилибрии, возникли проблемы с нормализацией URl на их стороне, которых ранее не было. Решение есть в канале https://t.me/anilibrix_plus, пока готовится патч, но я очень перегружен.

Нужно зайти в настройки, перейти к настройкам URL серверов и убрать слеш (косую черту) у обоих URL в конце, после чего желательно перезагрузить приложение.

**Comment by Viiprogrammer** [comment]
Исправлено в  836149e и будет включено в релиз  ext14
