### ISSUE TITLE
Как насчёт добавления нового прокси (на данную секунду, работает)

### ISSUE THREAD

**Issue by userkilled** [Viiprogrammer/anilibrix#31]
API: https://wwnd.anilib.moe

Static: https://static-libria.weekstorm.one/

🔀🔁
Взято с
 https://github.com/anilibria/anilibria-app/blob/develop/config.json

**Comment by Viiprogrammer** [comment]
> API: https://wwnd.anilib.moe
> 
> Static: https://static-libria.weekstorm.one/
> 
> 🔀🔁 Взято с https://github.com/anilibria/anilibria-app/blob/develop/config.json

Выбор домена не ограничен списком, там текстовое поле и в него можно ввести любой.

https://static-libria.weekstorm.one/ насколько помню вроде есть в предложенных в 13 версии, а вот https://wwnd.anilib.moe/ вполне можно

**Comment by Viiprogrammer** [comment]
https://wwnd.anilib.moe/ - отдает 403 forbidden
https://static-libria.weekstorm.one/  - есть в списке

**Comment by userkilled** [comment]
Прямой переход и правда даёт 403, но запрос к API работает, на приложении проверил, видео воспроизводится
