### ISSUE TITLE
Масштабирование окна "Картинка в картинке" не работает на EvilWM

### ISSUE THREAD

**Issue by delyfssflaggedagain** [Viiprogrammer/anilibrix#38]
https://github.com/user-attachments/assets/0caa7638-938e-4d9f-b126-ba51921111fd

**Comment by Viiprogrammer** [comment]
А можно по точнее? Что за система, de и прочее? Я не смогу это воспроизвести, не зная все это. Как я вижу в начале все работает, но почему-то перестает. PIP предоставляет Chromium, возможно это баг конкретной версии электрона, на нее я могу частично повлиять

**Comment by delyfssw** [comment]
Arch с EvilWM (де 9 лет хд)
как оказалось такая проблема с любым электрон приложением 
так что фикса скорее всего не дождусь

**Comment by Viiprogrammer** [comment]
> так что фикса скорее всего не дождусь

Ну я могу поиграть с версией в некоторых пределах, супер ультра актуал для приложения в данный момент мало актуален)

возможно где-то оно все же работает. В хромиуме у тебя тоже в PIP такая проблема?

**Comment by delyfssw** [comment]
> возможно где-то оно все же работает. В хромиуме у тебя тоже в PIP такая проблема?

да

**Comment by Viiprogrammer** [comment]
Не могу особо повлиять, решения пока нет, и видимо не предвидится.
