### ISSUE TITLE
в некоторых релизах не отображается статус

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#4]
на странице релиза у списка связанных релизов иногда не отображается статус ("завершен", "в работе"). он отсутствует на сайте анилибрии, поэтому его не подтягивает?
![Capture](https://github.com/AnimeHaze/anilibrix/assets/84020873/dd595716-14f4-4194-bdaa-1586b4aa4d66)

**Comment by Viiprogrammer** [comment]
Увы, судя по всему проблема на стороне либрии, и с этим я мало могу сделать, кроме скрытия статуса при отсутствии информации о нем. Спасибо!

![image](https://github.com/AnimeHaze/anilibrix/assets/17622604/c39992b2-f43d-445f-8662-f08b5769ca60)

**Comment by Viiprogrammer** [comment]
Исправлено в https://github.com/AnimeHaze/anilibrix/commit/aa6f2ab243b041fcb04929a11adf068fcf451c3c
