### ISSUE TITLE
залипает ползунок прогресса просмотра видео на таймлайне

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#42]
если мышкой захватить ползунок и переместить его по таймлайну. то он залипает и не движется. вывести из состояния залипания его можно нажатием на таймлайн для перемещения в другую точку.
если двигаться по таймлайну рывками, не трогая сам ползунок, то порядок, он не залипает.
![bug](https://github.com/user-attachments/assets/e9bd8535-446a-484f-a472-90f291c06624)
тут гифка качеством получше https://imgur.com/a/7UX7Mdk

**Comment by Viiprogrammer** [comment]
> если мышкой захватить ползунок и переместить его по таймлайну. то он залипает и не движется. вывести из состояния залипания его можно нажатием на таймлайн для перемещения в другую точку. если двигаться по таймлайну рывками, не трогая сам ползунок, то порядок, он не залипает.

Нужна информация об ОС, версии / сборке.

**Comment by azrylio** [comment]
Win 11 Pro, версия 23H2, сборка ОС 22631.2861
версия AnilibrixPlus v1.4.3-ext.13 (и прошлая релизная от 10,07 и текущая бэта без инкремента версии от 13,08)

**Comment by Viiprogrammer** [comment]
> Win 11 Pro, версия 23H2, сборка ОС 22631.2861 версия AnilibrixPlus v1.4.3-ext.13 (и прошлая релизная от 10,07 и текущая бэта без инкремента версии от 13,08)

Я так понимаю речь о том что вокруг ползунка остается "тень" и показывается тайминг пока не нажать за пределами прогресс бара?

Действительно ли это критично?

Просто это специфика UI кита Material который используется, не могу сказать что это баг, и в основном репозитории https://github.com/pavloniym/anilibrix эта штука работает идентично

**Comment by Viiprogrammer** [comment]
Блин, кажется я понял о чем речь... Ст оранный баг, попробую разобраться

**Comment by azrylio** [comment]
не, там не в тени дело. там ползунок (кружок), если его захватить мышью, потянуть и отпустить, он прям замирает наглухо, больше не движется, и если у его положения отображается время, то оно тоже не меняется. и так будет до того момента, пока не ткнешь курсором в прогресс-бар/тайм-лайн видео где-нибудь за пределами этого "кружка", чтобы его перекинуло в новое место без прикасания к нему самому.
если не получается воспроизвести, могу записать более подробное видео в лучшем разрешении, чем выше пожатое выкладывал (гитх не дал приложить нормальное видео из-за ограничений на размер), и положить куда-нибудь типа гуглодиска или я-диска, чтоб не пережимало его (ну или в тгм закунуть).

это не критично, жить не мешает никак. просто обнаружилось такое поведение, вот и зарепортил

**Comment by azrylio** [comment]
вот еще к этой же проблеме (решил проверить, а то вдруг дело в том, как я эксплуатирую приложение). если стоит скорость воспроизведения х2 или х1, поведение немного отличается.
на х2 залипший кружок мертво стоит на месте, если попробовать "прокрутить" прогресс видео стрелками на клавиатуре.
а на х1 при перемещении стрелками клавиатуры кружок (и время на нем) сдвигается (время меняется), но он не отлипает, так и остается замершим на месте
