### ISSUE TITLE
[пожелания] несколько пожеланий по навигации

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#43]
1. не хватает кнопки "подняться вверх" (к началу "страницы"). например, в "избранном" или в "каталоге", если спустился глубоко вниз страницы, потом возвращаться приходится интенсивным скроллингом (а если релизов много - уже получается невыстро). также на страницах самих релизов с большим кол-вом серий (например, "блич" или "черный клевер") приходится скролить мощно, если спустился вниз.
2.  не хватает какой-нибудь кнопки "продолжить просмотр". тот же релиз "блич", у него там 300+ серий. если просмотрено уже много серий, чтобы продолжить смотреть, приходится скроллить мощно вниз. а было бы удобно, если бы была просто кнопочка "продолжить просмотр", где-нибудь наверху страницы релиза. (похожий функционал уже есть на вкладке "релизы", там есть кнопка "смотреть", которая отправляет к просмотру последней серии).
3. еще очень не хватает кнопки "назад" для перехода на предыдущий уровень навигации. (например, заходишь на вкладку "каталог", долго скролишь вниз, потом заходишь в какой-нибудь релиз, почитал описание, не цепануло, захотел назад... никак. только снова тыкать вкладку "релизы", и снова скролить. это касается не только вкладки "релизы". удобно было бы возвращаться назад при переходе от релиза к релизу через "связанные релизы", например. или в том же "избранном", если релизов много, сначала долго спускаешься вниз, доходишь до нужного, дрогнула рука, промахиваешься и заходишь не туда, куда хотел, а в соседний. приходится снова идти на вкладку, снова скролить вниз... )

**Comment by Viiprogrammer** [comment]
> 3. еще очень не хватает кнопки "назад" для перехода на предыдущий уровень навигации. (например, заходишь на вкладку "каталог", долго скролишь вниз, потом заходишь в какой-нибудь релиз, почитал описание, не цепануло, захотел назад... никак. только снова тыкать вкладку "релизы", и снова скролить. это касается не только вкладки "релизы". удобно было бы возвращаться назад при переходе от релиза к релизу через "связанные релизы", например. или в том же "избранном", если релизов много, сначала долго спускаешься вниз, доходишь до нужного, дрогнула рука, промахиваешься и заходишь не туда, куда хотел, а в соседний. приходится снова идти на вкладку, снова скролить вниз... )

скролл в каталоге исправлен в бета версии, но да, я подумаю как можно добавить, тк есть кейс со связанным

с остальным вполне согласен

**Comment by Viiprogrammer** [comment]
1. Добавлен в 8ca9d2f37475fe79022f14b74a33d78ce674be6b
2. Добавлен в 4fb1fae3dd1e843d023ede4bd903d3cd1093bf81
3. Пока нет идей куда добавить

**Comment by Viiprogrammer** [comment]
В принципе считаю что более менее выполнено, а насчет 3‑го пункта, если есть идеи, можно создать новый ишью по этому поводу!
