### ISSUE TITLE
[пожелание] список войсеров, работавших над релизом

### ISSUE THREAD

**Issue by azrylio** [Viiprogrammer/anilibrix#5]
если это возможно, было бы круто к разделу с описанием релиза добавить также список войсеров, которые работали над релизом. как это сделано на самом сайте.

**Comment by Viiprogrammer** [comment]
Сделано, будет в следующей версии
![image](https://github.com/AnimeHaze/anilibrix/assets/17622604/0b88afa0-d10a-4bad-b6a9-70e8e518edbe)

**Comment by Viiprogrammer** [comment]
Добавлено в https://github.com/AnimeHaze/anilibrix/commit/262824e40f04e1cc3938e748d97a8dff5683f819
